version: "3.9"
services:
  preprocess_worker:
    build:
      context: ../geoint-dem-detection
      dockerfile: Dockerfile
    working_dir: /app 
    command: ["/app/start_preprocess.sh"] 
    environment:
      TOOLS_DIR: /app/geoint-dem-detection/tools
      DELIVERY_YEAR: ${DELIVERY_YEAR}
      TEMP_DIR: /app/temp
      DATA_ROOT: /app/data/
      DB_FILE: /app/data/db/inference.db
      RABBITMQ_HOST_INTERNAL: rabbitmq
      RABBITMQ_HOST: grizzly-rabbitmq
    volumes:
      - .:/app:cached
      - ../geoint-dem-detection:/app/geoint-dem-detection:ro
      - logs_volume:/app/logs
      - /skog-nas01/scan-data:/app/data:rw
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - grizzly
    deploy:
      replicas: 1

  inference_worker:
    build:
      context: ../geoint-dem-detection
      dockerfile: Dockerfile
    working_dir: /app
    command: ["/app/start_inference.sh"] 
    environment:
      INFERENCE_SCRIPT_DIR: /app/geoint-dem-detection/model
      TOOLS_SCRIPT_DIR: /app/geoint-dem-detection/tools
      ROOT_GEOINT_DIR: /app/geoint-dem-detection
      NVIDIA_VISIBLE_DEVICES: all
      MODEL_PATH: /app/data/models/DEMProcessing
      RABBITMQ_HOST_INTERNAL: rabbitmq
      RABBITMQ_HOST: grizzly-rabbitmq
      RUN_KOLBOTTEN: ${RUN_KOLBOTTEN}
      RUN_FANGSTGROP: ${RUN_FANGSTGROP}
      RUN_MYR: ${RUN_MYR}
      RUN_BACK: ${RUN_BACK}
      RUN_VAGAR: ${RUN_VAGAR}
      RUN_VAGAR_KORSPAR: ${RUN_VAGAR_KORSPAR}
      RUN_KORSPAR: ${RUN_KORSPAR}
      TORCH_HOME: /app/.cache/torch
    volumes:
      - .:/app:cached
      - ../geoint-dem-detection:/app/geoint-dem-detection:ro
      - logs_volume:/app/logs
      - /skog-nas01/scan-data:/app/data:rw
      - ./cache/torch:/app/.cache/torch
      - temp_output:/app/temp_output
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - grizzly

    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      

volumes:
  logs_volume:
    driver: local
  temp_output:
    driver: local
networks:
  geoint:
    driver: bridge
  grizzly:
    external: true